### ISSUE TITLE
网站的样式和图片全部挂掉了

### ISSUE THREAD

**Issue by MaosanDao** [flutterchina/flutter-in-action#110]

**Comment by wendux** [comment]
刷新一下试试  我这边正常

**Comment by MaosanDao** [comment]
> 刷新一下试试 我这边正常

刷新还是一样的，难道是要清除缓存么，系统是mac，浏览器是Chrome

**Comment by wendux** [comment]
你在什么地方？这是CDN不稳定导致，部分区域偶尔不可访问，不行的话，可以直接在github上阅读，目录地址：https://github.com/flutterchina/flutter-in-action/blob/master/docs/SUMMARY.md

**Comment by MaosanDao** [comment]
> 你在什么地方？这是CDN不稳定导致，部分区域偶尔不可访问，不行的话，可以直接在github上阅读，目录地址：https://github.com/flutterchina/flutter-in-action/blob/master/docs/SUMMARY.md

好的，非常感谢，目前就在github上读吧
