### ISSUE TITLE
【勘误】关于flutter-in-action/docs/chapter1/configuration.md

### ISSUE THREAD

**Issue by cuihee** [flutterchina/flutter-in-action#114]
flutter-in-action/docs/chapter1/configuration.md 中最后 安卓包配置问题 第4点 

原文
 “进入 File/ Settings/ Build, Execution, Deployment/ Gradle/ Android Studio 中，勾选上 Enable embedded Maven repository ，重启 Android Studio 即可解决”

应为
“进入 File/ Settings/ Build, Execution, Deployment/ BuildTools/ Gradle/ Android Studio 中，勾选上 Enable embedded Maven repository ，重启 Android Studio 即可解决”

**Comment by wendux** [comment]
已更正，以后勘误可以提PR哦
