### ISSUE TITLE
每个page中想要写Theme吗？。。。。

### ISSUE THREAD

**Issue by nur001** [flutterchina/flutter-in-action#118]
![screenshot_1551091247](https://user-images.githubusercontent.com/47020275/53331855-e1bb3f00-392c-11e9-897f-79a53983cbd9.png)
![screenshot_1551091240](https://user-images.githubusercontent.com/47020275/53331856-e1bb3f00-392c-11e9-9832-d92ee771c3a5.png)

登录页面没问题，但是其他页面没有变。。。（每个页面都要写Theme(.....)?）

**Comment by wendux** [comment]
全局主题可以在`MaterialApp` 上设置
