### ISSUE TITLE
chapter8 事件总线，示例代码存在一点问题

### ISSUE THREAD

**Issue by w4mxl** [flutterchina/flutter-in-action#123]
我按示例代码中的逻辑测试发现，bus.on("xx",(arg){}) 添加在了一个页面，这个页面每次加载会多次添加监听事件。这时当另一个页面（比如登录页面）触发bus.emit(“xx”);时，前面on的地方也会被多次调用。

**Comment by w4mxl** [comment]
我发现之所以会被多次添加监听事件，是因为我把bus.on放在了Widget build(BuildContext context) 方法体里面，这时页面setState会导致bus.on ("xx",(arg){}) 多次。

目前想到的解决方法是，把bus.on ("xx",(arg){}) 放在了页面的initState()方法体里面了。

作者如果看到觉得我理解没问题的话，请 close 吧。

**Comment by wendux** [comment]
理解，bus是全局的，添加后如果不off，就会一直存在，这是符合预期的, 开发者需要自己来释放。
