### ISSUE TITLE
关于自定义字体多人协作以及后续维护问题

### ISSUE THREAD

**Issue by JuanJuanZhang123** [flutterchina/flutter-in-action#128]
![image](https://user-images.githubusercontent.com/18701952/54197453-f425a300-44fe-11e9-83ca-6c34033f7ed1.png)
1、如上图所示，flutter支持自定义图标，按这种方式，后续如何进行自定义图标的增加、删减呢？
另外如果想使用自己设计的图片应该如何生成tff文件以及相应的dart文件呢？我查出来有一个http://fluttericon.com/ 但是也有维护等相关问题，同时转换的部分图标由线性转换为了实体填充。
2、如果需要多人协作的情况，如何避免自己加了新图标的文件被冲掉？
如有好的方法，请指教

**Comment by wendux** [comment]
1. 规范流程，比如字体更新由特定的人来做
2. 可以分拆多个文件，定义多个字体，彼此不修改对方的
