### ISSUE TITLE
书里的window下的安装方法，不太适用当前版本了。

### ISSUE THREAD

**Issue by luchenwei9266** [flutterchina/flutter-in-action#14]
书里提到windows下可以手动下载SDK，但似乎现在windows下flutter不能通过手动下载SDK来安装，必须通过git clone。

按照书里手动下载的话，会报错，并提示用git clone官方github库。

而且clone下来后，运行“flutter docter“命令还会报一个“Error: Unable to update Dart SDK. Retrying...“的错误，需要配置另外一个环境变量才能解决

**Comment by Taonce** [comment]
@luchenwei9266 我前天配置的，我刚才试了下，下载了最新的1.0结果不行了。。。

**Comment by Taonce** [comment]
@luchenwei9266 我刚刚重新下了一次，在https://flutter.io/docs/development/tools/sdk/archive#windows上面下载最新的，然后去解压，去解压目录里面运行flutter_console.bat就ok了

**Comment by luchenwei9266** [comment]
@Taonce 嗯，好的，谢谢了，我昨晚其实已经配置好了，不过我配的是v0.11.13，刚刚打开发现已经是1.0了。这样子的话，书里的window下的安装方法应该还是适用的
