### ISSUE TITLE
按google团队的介绍，Skia无论是android或ios应该都被打包最新的

### ISSUE THREAD

**Issue by dazsco** [flutterchina/flutter-in-action#149]
https://book.flutterchina.club/chapter1/flutter_intro.html
我看过google团队的介绍，Skia无论是android或ios应该都被打包，这样保证了即使Android版本过低，也能使用最新的渲染引擎。所以这一章作者可以在确认一下

`值得一提的是，由于Android系统已经内置了Skia，所以Flutter在打包APK(Android应用安装包)时，不需要再将Skia打入APK中`

**Comment by Vadaski** [comment]
是的，skia只与flutter sdk版本相关，此处flutter 软件工程师 Yuqian Li 也提到了
https://www.youtube.com/watch?v=OLjhAl7adGE

**Comment by wendux** [comment]
已更新
