### ISSUE TITLE
gitbook pdf 报错，使用gitbook 3.2.2 是版本问题吗？还是插件问题？

### ISSUE THREAD

**Issue by yxAnswer** [flutterchina/flutter-in-action#155]
Error: ENOENT: no such file or directory, stat 'C:\Users\ANSWER\AppData\Local\Temp\tmp-1039222lAgbF3bG06\gitbook\gitbook-plugin-prism\prism-coy.css'

**Comment by yxAnswer** [comment]
EbookError: Error during ebook generation: ������̫����
现在报这种错误。。都不知道编码格式到底是什么，试了很多次，也不知道哪错了怎么办？

**Comment by yxAnswer** [comment]
EbookError: Error during ebook generation: The command line is too long.

**Comment by yxAnswer** [comment]
flutter-in-action> gitbook pdf
info: 13 plugins are installed
info: 10 explicitly listed
info: loading plugin "search-pro"... OK
info: loading plugin "ace"... OK
info: loading plugin "splitter"... OK
info: loading plugin "toggle-chapters"... OK
info: loading plugin "prism"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "theme-default"... OK
info: found 85 pages
info: found 214 asset files
warn: "options" property is deprecated, use config.get(key) instead
warn: "options.generator" property is deprecated, use "output.name" instead

EbookError: Error during ebook generation: The command line is too long.

**Comment by yxAnswer** [comment]
和系统有关系，我再windows下是不行的，，但是在 linux  和 mac下我都成功了。。。。

**Comment by yxAnswer** [comment]
解决了

**Comment by forvicky** [comment]
> 解决了

怎么解决的？

**Comment by yxAnswer** [comment]
> > 解决了
> 
> 怎么解决的？

就用mac或者linux 就行，windows下先别整pdf了，windows下可以用在线看。。win10不是可以直接装个linux 内核吗？你也可以试试

**Comment by Akateason** [comment]
TypeError: this element does not have children or attributes
