### ISSUE TITLE
被人抄袭,  并且人家说是自己写的...  

### ISSUE THREAD

**Issue by zhangrunhao** [flutterchina/flutter-in-action#161]
https://crifod.github.io/2018/12/05/flutter_chapter2/index/

被人抄了...

很好奇的问, 这种情况怎么处理..

**Comment by wendux** [comment]
多谢反馈，抄倒没什么，把打赏二维码换了就不能忍了....

**Comment by zhangrunhao** [comment]
> 多谢反馈，抄倒没什么，把打赏二维码换了就不能忍了....

是啊, 那要怎么处理呢?

**Comment by zhangrunhao** [comment]
截图取证, 真是心疼作者...   有些人总是这么恶心, 好好的一个开源书, 这样搞.
![截图URL]
(http://zhangrunhao.oss-cn-beijing.aliyuncs.com/github/WechatIMG1.jpeg)

**Comment by shikechen** [comment]
这家伙GitHub https://github.com/crifod

**Comment by moonljt521** [comment]
@shikechen 头像还挺炫。。。

**Comment by zhangrunhao** [comment]
博客找不到了, 给关了
