### ISSUE TITLE
Widget简介中父项管理子项状态时描述父项为StatelessWidget

### ISSUE THREAD

**Issue by leoyuuu** [flutterchina/flutter-in-action#162]
对于父widget来说，管理状态并告诉其子widget何时更新通常是比较好的方式。 例如，IconButton是一个图片按钮，但它是一个无状态的widget，因为我们认为父widget需要知道该按钮是否被点击来采取相应的处理。

在以下示例中，TapboxB通过回调将其状态导出到其父项。由于TapboxB不管理任何状态，因此它的父类为StatelessWidget。

**Comment by wendux** [comment]
fixed
