### ISSUE TITLE
弹性布局的 Expanded例子 报错

### ISSUE THREAD

**Issue by free19910219** [flutterchina/flutter-in-action#165]
class FlexLayoutTestRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        //Flex的两个子widget按1：2来占据水平空间  
        Flex(
          direction: Axis.horizontal,
          children: <Widget>[
            Expanded(
              flex: 1,
              child: Container(
                height: 30.0,
                color: Colors.red,
              ),
            ),
            Expanded(
              flex: 2,
              child: Container(
                height: 30.0,
                color: Colors.green,
              ),
            ),
          ],
        ),
        Padding(
          padding: const EdgeInsets.only(top: 20.0),
          child: SizedBox(
            height: 100.0,
            //Flex的三个子widget，在垂直方向按2：1：1来占用100像素的空间  
            child: Flex(
              direction: Axis.vertical,
              children: <Widget>[
                Expanded(
                  flex: 2,
                  child: Container(
                    height: 30.0,
                    color: Colors.red,
                  ),
                ),
                Spacer(
                  flex: 1,
                ),
                Expanded(
                  flex: 1,
                  child: Container(
                    height: 30.0,
                    color: Colors.green,
                  ),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}

direction 为Axis.horizontal 时需要指定对齐方式  textDirection: TextDirection.ltr,

**Comment by wendux** [comment]
书中所有路由Widget示例, 凡是没有被Scaffold 包的，在执行时都会被Scaffold 包一下，包一下就能正常运行，示例代码省去是为了简洁。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
