### ISSUE TITLE
chapter4/row_and_column.md 的翻译问题

### ISSUE THREAD

**Issue by see311** [flutterchina/flutter-in-action#170]
CrossAxis翻译成交叉轴比较好，纵轴给人感觉是垂直方向上的

**Comment by see311** [comment]
看到后面GridView一章，
> crossAxisSpacing：横轴方向子元素的间距。
这里又翻译成了横轴，我觉得都统一叫交叉轴比较好。
在CSS中的flex布局里cross axis被翻译为交叉轴

**Comment by wendux** [comment]
CrossAxis是相对于主轴而言的，”交叉轴“感觉很怪，读者能理解意思就行，不必纠结
