### ISSUE TITLE
widget修改不会导致State创建的内容有疑问

### ISSUE THREAD

**Issue by fyyyr** [flutterchina/flutter-in-action#189]
在《Widget简介》这一章关于State的部分，有如下内容：
```
State中有两个常用属性：

widget，它表示与该State实例关联的widget实例，由Flutter framework动态设置。注意，这种关联并非永久的，因为在应用声明周期中，UI树上的某一个节点的widget实例在重新构建时可能会变化，但State实例只会在第一次插入到树中时被创建，当在重新构建时，如果widget被修改了，Flutter framework会动态设置State.widget为新的widget实例。
```

其中提到：
```
UI树上的某一个节点的widget实例在重新构建时可能会变化，但State实例只会在第一次插入到树中时被创建，当在重新构建时，如果widget被修改了，Flutter framework会动态设置State.widget为新的widget实例。
```

这其中的`重新构建`，指的应该是Widget.canUpdate()返回为false，导致Element重新创建吧？
于是我创建了一个StatefulWidget，为其附加了key。这样修改这个Widget时，key就会发生变化，从而Widget.canUpdate()返回为false。
然而经过测试，我发现每次对Widget进行修改，都会调用State的构造函数和初始化函数。
也就是说当重新构建Element时，并非是将已有的State.widget指向新的widget实例，而是直接创建了一个新的State，已有的State应该是被丢弃了。  
若去掉key属性，则对Widget修改时，Widget.canUpdate()返回为true，虽然Element会更新，但State的构造函数和初始化函数没有被调用。  

求问这个地方是否是我对书中内容理解不到位？

**Comment by wendux** [comment]
重新构建即rebuild，就是指重新调用build方法
