### ISSUE TITLE
对于通知那里,博主你本类发,本类接....这样有何意义?

### ISSUE THREAD

**Issue by pheromone** [flutterchina/flutter-in-action#220]
对于通知那里,博主你本类发,本类接....这样有何意义?

**Comment by wendux** [comment]
通知是widget树中自低向上的一种事件传递机制，同一个类中构建的Widget树也是有层次的啊，和是否同意个类没关系

**Comment by pheromone** [comment]
如果需要A树中的a对B树中b发呢?    我使用event_bus 可以,难道难道自带的只能在一棵树上收发?
