### ISSUE TITLE
WillPopScopeTestRoute

### ISSUE THREAD

**Issue by JoinJustForCool** [flutterchina/flutter-in-action#230]
return Scaffold(
      appBar: AppBar(title: Text('ddd')),
      body: new WillPopScope(
          onWillPop: () async {
            if (_lastPressedAt == null ||
                DateTime.now().difference(_lastPressedAt) > Duration(seconds: 1)) {
              //两次点击间隔超过1秒则重新计时
              _lastPressedAt = DateTime.now();
              return false;
            }
            return true;
          },
          child: Container(
            alignment: Alignment.center,
            child: Text("1秒内连续按两次返回键退出"),
          )
      )
    );

WillPopScope  需要添加在body后面 直接复制作者的代码会显示黑屏 和不友好的页面。  

最后感谢楼主分享关于flutter的文章和书籍； 希望您的书越来越完美！！！

**Comment by wendux** [comment]
示例是省略了Scaffold的

**Comment by JoinJustForCool** [comment]
嗯嗯




| |
邵立德
|
|
邮箱：shao_li_de@163.com
|

签名由 网易邮箱大师 定制

On 08/09/2019 18:19, wendu wrote:

Closed #230.
