### ISSUE TITLE
登录异常

### ISSUE THREAD

**Issue by SimonWangChen** [flutterchina/flutter-in-action#285]
无法登录
使用Simulator
翻墙后:
flutter: DioError [DioErrorType.DEFAULT]: HttpException: , uri = //api.github.com:443
翻墙前:
flutter: DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Operation timed out, errno = 60, address = 10.1.10.250, port = 55652

**Comment by wendux** [comment]
示例中是设置了代理的，先看看有没有注掉


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by SimonWangChen** [comment]
为什么要设置代理呢?

**Comment by SimonWangChen** [comment]
原来只能用用户名, 不能用邮箱
