### ISSUE TITLE
文字错误

### ISSUE THREAD

**Issue by plumhly** [flutterchina/flutter-in-action#296]
### 4.6 对齐与相对定位 
  Alignment坐标转换公式有误：
      (Alignment.x*childWidth/2+childWidth/2, **Alignment.x** * childHeight+childHeight/2)
或许应该为
     (Alignment.x*childWidth/2+childWidth/2, **Alignment.y** * childHeight+childHeight/2)

**Comment by wendux** [comment]
笔误，已更正
