### ISSUE TITLE
4.1 布局类组件简介，RichText父类错误

### ISSUE THREAD

**Issue by Zheng-Shuo** [flutterchina/flutter-in-action#301]
4.1 布局类组件简介章节中说"而RichText才是继承自LeafRenderObjectWidget。所以为了方便叙述，我们也可以直接说Text属于LeafRenderObjectWidget"，而源码中RichText是继承MultiChildRenderObjectWidget的，https://github.com/flutter/flutter/blob/5caad71f1dce1db0e629dfbe1b33c9bddb3b602b/packages/flutter/lib/src/widgets/basic.dart#L5007

**Comment by wendux** [comment]
已修改到最新，本书中所述的继承关系都是以本书撰写之时Flutter SDK为准的，Flutter SDK不同版本会有调整。
