### ISSUE TITLE
第九章动画介绍勘误

### ISSUE THREAD

**Issue by zhaojiewen** [flutterchina/flutter-in-action#312]
**原文粗体：Flutter中正是通过这种方式封装了很多动画，如：FadeTransition、ScaleTransition、SizeTransition、FractionalTranslation等，很多时候都可以复用这些预置的过渡类。**

阅读源码，结果如下：ScaleTransition、SizeTransition，是通过继承AnimatedWidget实现，FadeTransition 是通过RenderAnimatedOpacity 实现。
FractionalTranslation 不具备动画功能，只是修改位置！

**Comment by wendux** [comment]
已修改
