### ISSUE TITLE
9.4hero动画：demo运行报错

### ISSUE THREAD

**Issue by daisyUnicorn** [flutterchina/flutter-in-action#319]
提示：
InkWell widgets require a Material widget ancestor.
运行环境：
Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (4 months ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
解决方案：
Wrap the InkWell Class with the Material Class

**Comment by wendux** [comment]
书中只是部分代码，随书源码运行是没问题的
