### ISSUE TITLE
书籍错别字修正

### ISSUE THREAD

**Issue by loveRose** [flutterchina/flutter-in-action#32]
开头第一个 “缘由”里面有句话叫：当然还有另外一个原因就是要做实体书的“化”。。。这里的化应该是“话”

**Comment by 381386453** [comment]
按钮页面中，蓝色背景部分
细心的读者可能会发现这个按钮没有阴影(点击之后也没有)，这样会显得没有质感。其实这也很容易，将上面的FlatButton换成RaiseButton就行，
RaiseButton   应该改为 RaisedButton

**Comment by vckkk** [comment]
图片和Icon一节中，在定义MyIcons时，误将‘book’写成了‘bool’
