### ISSUE TITLE
文字缺失

### ISSUE THREAD

**Issue by Arrrrray** [flutterchina/flutter-in-action#325]
第一章第三节：搭建Flutter开发环境中，更新环境变量这个小段下面，有文字缺失
![image](https://user-images.githubusercontent.com/26154710/68562247-c88afc00-0483-11ea-94cc-94835145cba0.png)

是不是想说而不是Git for Windows这个工具

**Comment by wendux** [comment]
不是，应该删掉括号里面的内容，已修改
