### ISSUE TITLE
ScrollBar原理描述好像有误？

### ISSUE THREAD

**Issue by l1shu** [flutterchina/flutter-in-action#335]
6.1节中说：

> Scrollbar和CupertinoScrollbar都是通过ScrollController来监听滚动事件来确定滚动条位置的

6.6节中又说：

> 可滚动组件在滚动时会发送ScrollNotification类型的通知，ScrollBar正是通过监听滚动通知来实现的

两者貌似冲突了，前者说ScrollBar是通过ScrollController实现的，后者说ScrollBar通过监听通知实现

**Comment by wendux** [comment]
已修改
