### ISSUE TITLE
Type _typeOf<T>() => T;有啥用？

### ISSUE THREAD

**Issue by l1shu** [flutterchina/flutter-in-action#336]
7.3节中的

> `Type _typeOf<T>() => T;`

这个函数有什么作用？有点多此一举的感觉

**Comment by wendux** [comment]
该方法用于在Dart中获取模板类型。为什么要这么做？因为下面代码编译会报错：
![image](https://user-images.githubusercontent.com/20411648/69518610-fba8b180-0f92-11ea-9f55-0670e0a6197b.png)

所以想办法获取类型`InheritedProvider<T>`，下面这样的代码同样会报错：
![image](https://user-images.githubusercontent.com/20411648/69518591-efbcef80-0f92-11ea-8dbc-f18cd066fc68.png)

目前Dart想要获取带参数模板的类型的方式只有一种，就是定义这么一个函数`Type _typeOf<T>() => T;`，然后：
```dart
    final type = _typeOf<InheritedProvider<T>>();
    final provider =  context.inheritFromWidgetOfExactType(type) as InheritedProvider<T>；
```

**Comment by l1shu** [comment]
明白了，感谢回复~
