### ISSUE TITLE
《包管理》章节语句修改

### ISSUE THREAD

**Issue by mingshengxiao** [flutterchina/flutter-in-action#43]
在第一段的最后一句是：
本节我们主要介绍一下flutter下如何是使用配置文件pubspec.yaml（位于项目根目录）来管理第三方依赖包。
这句读起来有点拗口，改成
本节我们主要介绍一下flutter如何使用配置文件pubspec.yaml（位于项目根目录）来管理第三方依赖包。
是否会更通顺易读呢？

**Comment by wendux** [comment]
已修改
