### ISSUE TITLE
《流式布局》中Flow代码片段中代码错误

### ISSUE THREAD

**Issue by AramisLi** [flutterchina/flutter-in-action#61]
在《流式布局》这章中，Flow的代码片段paintChildren这个方法中，如果想要实现图片的效果```x += context.getChildSize(i).width + margin.left + margin.right;``` 要移出eles外。即
```
void paintChildren(FlowPaintingContext context) {
  for (int i = 0; i < context.childCount; i++) {
    if (w < context.size.width) {
      ···
    }else{
     ···
    }
       x += context.getChildSize(i).width+ margin.left + margin.right;
  }
}
```

**Comment by wendux** [comment]
已更正

**Comment by hanqiao8866** [comment]
为什么要移出else之外，移出去之后就错了，context.getChildSize(i).width + margin.left + margin.right这句话还是应该放在else之内，else语句是判断当需要换行的时候，换行后每次遍历需要重新计算子widget的x值。
