### ISSUE TITLE
《ListView》章节中，InfiniteListView报错setState() or makeNeedsBuild() called during build.

### ISSUE THREAD

**Issue by AramisLi** [flutterchina/flutter-in-action#64]
解决方法：
void _retrieveData() {
    Future.delayed(Duration(seconds: 2)).then((e) {
      _words.insertAll(_words.length - 1,
          generateWordPairs().take(20).map((e) => e.asPascalCase).toList());
    }).then((e){
      setState(() {
      });
    });
  }

**Comment by wendux** [comment]
我这边没问题啊，对比了一下示例代码，你的代码就多了一个then，这应该没啥影响吧。
示例代码如下：
```dart
    Future.delayed(Duration(seconds: 2)).then((e) {
      _words.insertAll(_words.length - 1,
          //每次生成20个单词
          generateWordPairs().take(20).map((e) => e.asPascalCase).toList()
      );
      setState(() {
        //重新构建列表
      });
    });
```
