### ISSUE TITLE
《数据共享-InheritedWidget》

### ISSUE THREAD

**Issue by AramisLi** [flutterchina/flutter-in-action#66]
1. 若要与图片的显示效果相同，_InheritedWidgetTestRouteState的build方法，根节点应该是Scaffold

2. 最后一段，“应该在didChangeDependencies()中做什么？”中“昂贵的操作” 猜测是 “耗时的操作”

**Comment by wendux** [comment]
路由启动时都会用Scaffold先包一下路由Widget的，所以在路由定义中并没有`Scaffold`, 要不然每个示例都多一层Scaffold，没必要。“昂贵的操作” 一般都会伴随着 “耗时”，在英文表述中为expensive operation，“耗时操作“ 确实更通俗一点。
