### ISSUE TITLE
开发效率问题

### ISSUE THREAD

**Issue by Lizhooh** [flutterchina/flutter-in-action#68]
![qq 20181228202502](https://user-images.githubusercontent.com/19299088/50515307-bbb92000-0ade-11e9-98e6-98b8a8e3211b.png)

这里 RN/Weex 为代表的开发效率应该是高才对，**种种实践表明，RN/Weex 的开发效率比 Flutter 还要快。（快很多）**，有点误导人了。

**Comment by Lizhooh** [comment]
QT 开发效率最慢，大家都懂。

**Comment by wendux** [comment]
1. 最后一行描述不准确，应该是flutter高，QT低。这个要改一下。
1.至于“RN/Weex 的开发效率比 Flutter 还要快。”  ，这个笔者觉得Flutter开发流还是很快的，对开发效率影响最大的就是热更新和调试，这两者flutter支持的比较好。另外开发效率和开发者自身的熟练程度也有关，两者开发效率持平应该是相对客观的，但笔者不认为RN/Weex 的开发效率要比 Flutter 快很多。

**Comment by wayson** [comment]
@Lizhooh 开发时间=写代码+调试+修bug。RN写代码所花的时间很短，但是调试或者修bug的时间会随着项目发展而程指数级增加。我们team已经被RN折磨得不成样子了，所以来看看flutter是否能代替RN。

**Comment by Lizhooh** [comment]
@wendux 调试不会花太多时间，是不是姿势不对。
