### ISSUE TITLE
原始指针事件处理代码测试不通过

### ISSUE THREAD

**Issue by r17171709** [flutterchina/flutter-in-action#72]
你好，我按照文章中的示例代码进行测试，好像Behavior均未实现如图文所示的效果

**Comment by r17171709** [comment]
@wendux 好像不是吧，我直接看chapter8里面的listener.md，HitTestBehavior.translucent添加之后一样不能穿透。我的flutter版本是1.0.0+1

**Comment by r17171709** [comment]
@wendux 你好，我测的结果是，注释掉translucent之后，点击非文本区域，控制台只会打印“down0”，点击文本区域，控制台只会打印“down1”。放开注释之后，非文本区域打印“down1”、“down0”，文本区域只会打印“down1”

**Comment by r17171709** [comment]
@wendux 那文章的内容不就是有误了吗，应该是非文本区域没有添加translucent只会打印down0，而不是down1

**Comment by wendux** [comment]
已更正
