### ISSUE TITLE
第4章流式布局Flow

### ISSUE THREAD

**Issue by opengit** [flutterchina/flutter-in-action#77]
`x += context.getChildSize(i).width + margin.left + margin.right;`应该放到else内~~
如图：
![image](https://user-images.githubusercontent.com/12468408/50734680-7df28080-11dd-11e9-8a2d-05495797eddc.png)

**Comment by opengit** [comment]
看到已有一个issue在讨论，`x += context.getChildSize(i).width + margin.left + margin.right;`放到外面的话，if中的`x=w+margin.left;`就必须移除，不然得到的效果是：
![image](https://user-images.githubusercontent.com/12468408/50734717-4506db80-11de-11e9-9e31-959dcea644b6.png)

**Comment by wendux** [comment]
已更正
