### ISSUE TITLE
文件操作如何读取assets下的文件

### ISSUE THREAD

**Issue by Nealyang** [flutterchina/flutter-in-action#80]
示例中```new File('$dir/counter.txt');``` 想咨询下，这个counter.txt存放在flutter项目的哪里？如果我想在assets下存放一个文件，然后读取该如何获取路径？

**Comment by mofada** [comment]
看这个https://flutterchina.club/assets-and-images/.
Future<String> loadAsset() async {
  return await rootBundle.loadString('assets/config.json');
}

**Comment by mofada** [comment]
@Nealyang 
看这个https://flutterchina.club/assets-and-images/.
Future loadAsset() async {
return await rootBundle.loadString('assets/config.json');
}

**Comment by Nealyang** [comment]
多谢，上次绕了个弯路，已经解决了~
