### ISSUE TITLE
Hero动画中的demo代码

### ISSUE THREAD

**Issue by crazy365966834** [flutterchina/flutter-in-action#90]
1. PageScaffold 是什么？是不是可以换成Scaffold。
2. 路由B中的代码，有个“,”写成了“，”。

**Comment by zhp475433752** [comment]
PageScaffold 找不到啊 这个是什么

**Comment by crazy365966834** [comment]
> PageScaffold 找不到啊 这个是什么

“Hero动画”一节中的示例代码，https://github.com/flutterchina/flutter-in-action/blob/master/docs/chapter9/hero.md

有个child，使用了PageScaffold。但是我未能找到相关的api。是不是应该用 Scaffold？

**Comment by VDshixiaoming** [comment]
PageScaffold是引用哪个包的？

**Comment by qiuziz** [comment]
同问，只找到`CupertinoPageScaffold` 没有`PageScaffold`

**Comment by shikechen** [comment]
服。。作者也不回答一下。。

**Comment by shikechen** [comment]
亲试，换成Scaffold可以，修改部分参数。

**Comment by wendux** [comment]
书中只是部分核心源码，完整示例可以参考随书源码。
