### ISSUE TITLE
Json 转 model : Unsupported operation: The class `` has no default constructor.

### ISSUE THREAD

**Issue by Hitomis** [flutterchina/flutter-in-action#92]
[INFO] Generating build script...
[INFO] Generating build script completed, took 281ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 103ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 653ms

[INFO] Running build...
[INFO] Running build completed, took 16ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 65ms

[SEVERE] json_serializable on lib/http/mo/template.dart (cached):
Error running JsonSerializableGenerator
Unsupported operation: The class `` has no default constructor.
[SEVERE] Failed after 99ms
pub finished with exit code 1

执行 mo.sh 文件一直报错，以上是执行日志。

**Comment by Hitomis** [comment]
上面是 shell 缓存造成的错误。已经好了。但是目前执行成功，没有dart文件输出。下面是日志
[INFO] Generating build script...
[INFO] Generating build script completed, took 331ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 104ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 650ms

[INFO] Running build...
[INFO] Running build completed, took 13ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 42ms

[INFO] Succeeded after 63ms with 0 outputs (0 actions)

**Comment by wendux** [comment]
可以给脚本下断点排错，数中的代码只能保证当时有效，依赖库更新后无法保证
